{{- define "k8s" -}}
{{ include "k.secret" . }}
---
{{ include "k.role" . }}
---
{{ include "k.serviceaccount" . }}
---
{{ include "k.rolebinding" . }}
---
{{- if eq "job" .runner.type }}
{{- if .runner.create }}
{{ include "k.job" . }}
{{- end }}
{{- else if eq "cronjob" .runner.type }}
{{- if .runner.create }}
{{ include "k.cronjob" . }}
{{- end }}
{{- else if eq "none" .runner.type }}
{{- else }}
{{- fail "runner must be one of job, cronjob, or none" }}
{{- end }}
{{- end }}
