apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  {{ template "iter8-autox.labels" . }}
data:
  resource-config.yaml: | 
    resources: 
    {{- range $r := .Values.resources }}
    {{- if eq $r "deployment" }}
    - group: apps
      version: v1
      resource: deployment
    {{- end }}
    {{- if eq $r "service" }}
    - version: v1
      resource: service
    {{- end }}
    {{- end }}
    namespaces:
{{ toYaml .Values.namespaces | indent 4 }}
  group-config.yaml: |
    groups:
      {{- range $name, $groups := .Values.groups }}
      - {{ $name }}:
          charts:
          {{- range $g := $groups }}
            - repo: {{ $g.repo }}
              name: {{ $g.chartName }}
              valuesFileURL: {{ $g.valuesFileURL }}
          {{- end }}
        {{- end }}
