apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Release.Name }} 
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.iter8lib.iter8Image }}
        command: ['iter8', 'autox', '--config', '/autox/apps.yaml']
        volumeMounts:
        - name: autox
          mountPath: "/autox"
          readOnly: true
      volumes:
      - name: autox
        secret:
          name: {{ .Release.Name }}
