apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.gatewayName }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
{{- with (index .Values.modelVersions 0) }}
    - {{ $.Values.serviceName }}.{{ default .namespace "modelmesh-serving" }}
    - {{ $.Values.serviceName }}.{{ default .namespace "modelmesh-serving" }}.svc
    - {{ $.Values.serviceName }}.{{ default .namespace "modelmesh-serving" }}.svc.cluster.local
{{- end }}
