{{- $versions := include "resolve.modelVersions" . | mustFromJson }}

{{- if eq "external" .Values.templateName }}
  {{ include "external.service" . }}
---
  {{ include "external.gateway" . }}

{{- else if eq "initialize" .Values.templateName }}
  {{ include "initial.virtualservice" . }}
---
  {{- if eq "blue-green" .Values.trafficStrategy }}
    {{ include "routemap-bluegreen" . }}
  {{- else if eq "canary" .Values.trafficStrategy }}
    {{ include "routemap-canary" . }}
  {{- else if eq "mirror" .Values.trafficStrategy }}
    {{ include "routemap-mirror" . }}
  {{- else }}
    {{ fail "Unknown trafficStrategy"}}
  {{- end }}
---
  {{- if eq "blue-green" .Values.trafficStrategy}}
    {{- range $i, $v := $versions }}
      {{ include "create.weight-config" (unset $v "weight") }}
    {{- end }}
  {{- end }}

{{- else if eq "modify-weights" .Values.templateName }}
  {{- if eq "blue-green" .Values.trafficStrategy}}
    {{- range $i, $v := $versions }}
      {{ include "create.weight-config" $v }}
---
    {{- end }}
  {{- end }}

{{- end }}
