apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.modelName }}
spec:
  gateways:
  - {{ .Values.gatewayName }}
  hosts:
{{- with (index .Values.modelVersions 0) }}
  - {{ $.Values.serviceName }}.{{ default .namespace "modelmesh-serving" }}
  - {{ $.Values.serviceName }}.{{ default .namespace "modelmesh-serving" }}.svc
  - {{ $.Values.serviceName }}.{{ default .namespace "modelmesh-serving" }}.svc.cluster.local
{{- end }}
  http:
  - route:
    - destination:
        host: {{ .Values.modelmeshServingEndpoint }}
        port:
          number: {{ .Values.modelmeshServingPort }}
      headers:
        request:
          set:
            mm-vmodel-id: "{{ (index .Values.modelVersions 0).name }}"