### default model mesh serving endpoints
modelmeshServingEndpoint: modelmesh-serving.modelmesh-serving.svc.cluster.local
modelmeshServingPort: 8033

### iter8Version is the minor version of Iter8
iter8Version: v0.13
