targetEnv: kserve-modelmesh
externalAccess: true
serviceName: mm-external
gatewayName: mm-external-gateway
trafficStrategy: blue-green
modelName: wisdom
modelVersions:
- name: wisdom-primary
- name: wisdom-canary
  namespace: modelmesh-serving
  weight: 50

### default model mesh serving endpoints
modelmeshServingEndpoint: modelmesh-serving.modelmesh-serving.svc.cluster.local
modelmeshServingPort: 8033

### iter8Version is the minor version of Iter8
iter8Version: v0.13
