apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  annotations: 
    iter8.tools/revision: {{ .Release.Revision | quote }}
data:
  abn-config.yaml: | 
    resources: 
    {{- range $r := .Values.resources }}
    {{- if eq $r "deployments" }}
    - group: apps
      version: v1
      resource: deployments
    {{- end }}
    {{- if eq $r "services" }}
    - version: v1
      resource: services
    {{- end }}
    {{- end }}
    namespaces:
    - {{ .Release.Namespace }}