apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  {{ template "iter8-abn.labels" . }}
data:
  abn-config.yaml: | 
    resources: 
    {{- range $r := .Values.resources }}
    {{- if eq $r "deployments" }}
    - group: apps
      version: v1
      resource: deployments
    {{- end }}
    {{- if eq $r "services" }}
    - version: v1
      resource: services
    {{- end }}
    {{- end }}
    namespaces:
{{ toYaml .Values.namespaces | indent 4 }}