apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: foo
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
data:
  abn-config.yaml: | 
    resources: 
    {{- range $r := .Values.resources }}
    {{- if eq $r "deployments" }}
    - group: apps
      version: v1
      resource: deployments
    {{- end }}
    {{- if eq $r "services" }}
    - version: v1
      resource: services
    {{- end }}
    {{- end }}
    namespaces:
{{ toYaml .Values.namespaces | indent 4 }}