apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  {{ template "iter8-abn.labels" . }}
data:
  abn-config.yaml: | 
  {{- range $ns, $apps := .Values.applications }}
    {{ $ns }}:
      {{- range $nm, $config := $apps }}
      {{ $nm }}:
        maxNumCandidates: {{ default 1 $config.maxNumCandidates }}
        resources: 
        {{- range $r := $config.resources }}
        {{- if eq $r "deployment" }}
        - group: apps
          version: v1
          resource: deployments
        {{- else if eq $r "service" }}
        - version: v1
          resource: services
        {{- else if eq $r "ksvc" }}
        - group: serving.knative.dev
          version: v1
          resource: services
        {{- end }}
        {{- end }}
      {{- end }}
  {{- end }}