apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  annotations:
    iter8.tools/revision: {{ .Release.Revision | quote }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  ports:
  - port: 80