name: Release Charts

on:
  push:
    branches:
    - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Iter8"
          git config user.email "iter8tools@gmail.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        with:
          config: config.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Invoke integration tests
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: integration tests
          token: ${{ secrets.PERSONAL_TOKEN }}